### ISSUE TITLE
One false positive

### ISSUE THREAD

**Issue by dreimer1986** [dummylabs/thewatchman#1]
First THANKS for this addon. I waited ages for such a scanning tool to easily fix my dozens automations etc and now here it is. Fixed about 20 errors that were hidden deep in my yamls. Now for one think that it complains about, but that is no error:

```
+--------------------------------+---------+--------------------------------------------------------------+
| Entity                         | State   | Location                                                     |
+--------------------------------+---------+--------------------------------------------------------------+
| timer.finished                 | missing | automations.yaml:269,333,758,907                             |
+--------------------------------+---------+--------------------------------------------------------------+
```

The corresponding automations look lik this:

```
- id: zigbee-join-timer-deaktivieren
  alias: Zigbee Join nach Timer deaktivieren
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    entity_id: input_boolean.zigbee_permit_join
  mode: single
```

This is a quite existing event type and no missing entity. So it's a false positive.
