### ISSUE TITLE
icon: 'sfsymbols:switch.2' shows as unavailable entitiy switch.2

### ISSUE THREAD

**Issue by jensihnow** [dummylabs/thewatchman#116]
Hi,

I do have an automation which shows an error (" switch.2 [missing] office.yaml ") in Watchman

```
# Send reminder if desk power is still on
- alias: "123"
  trigger:
    - platform: time
      at: "19:00:00"
  condition:
    - condition: state
      entity_id: switch.xyz
      state: 'on'
  action:
    - service: notify.ios_devices
      data_template:
        title: "Message Title"
        message: >-
          Message Message Message
        data:
          priority: 0
          actions:
             - action: "DESKOFF"
               title: "Turn off!"
               icon: 'sfsymbols:switch.2'
```

Apparently, Watchman is having issues with the icon configuration, see data part of the action. 

> icon: 'sfsymbols:switch.2'

One can ignore the entitiy _switch.2_ within the service configuration, but would be nice if such configurations wouldn't be listed as issue.

Thanks for building Watchman!
