### ISSUE TITLE
Failed to call service watchman.report. Unknown service parameter: ignored_items.

### ISSUE THREAD

**Issue by pauldcomanici** [dummylabs/thewatchman#126]
I'm trying to run watchman with ignored_items option and I get this error
```
Failed to call service watchman.report. Unknown service parameter: ignored_items.
```

From developer tools -> services -> yaml mode I tried:
```
service: watchman.report
data:
  create_file: true
  send_notification: false
  parse_config: false
  chunk_size: false
  ignored_items: "*.0_lv1_*,binary_sensor.0_ct_smoke_smoke,binary_sensor.1_dm_smoke_smoke"
```

I'm doing something wrong or ignored_items doesn't work?
