### ISSUE TITLE
Consider supported_features and example in services.yaml as valid

### ISSUE THREAD

**Issue by chemelli74** [dummylabs/thewatchman#130]
In `services.yaml`, integrations can specify a `supported_features` key to filter entities.
Here an example:

```yaml
backup:
  name: Backup
  description: Backup the ESPSomfy Device
  target:
    entity:
      integration: espsomfy_rts
      domain: button
      supported_features:
        - fan.FanEntityFeature.OSCILLATE
```

Here the documentation reference: [Filtering service fields](https://developers.home-assistant.io/docs/dev_101_services/#filtering-service-fields)

**Comment by chemelli74** [comment]
Same goes for the `example` key:

```yaml
replace_sensor:
  description: Replaces an external sensor
  # target:
  #   entity:
  #     domain: plant
  fields:
    meter_entity:
      name: Meter entity
      description: The meter entity to replace the sensor for
      example: plant.my_plant_current_temperature
      required: true
      selector:
        entity:
          domain: sensor
          integration: plant
```
