### ISSUE TITLE
Unable to call service

### ISSUE THREAD

**Issue by pedolsky** [dummylabs/thewatchman#147]
Using service watchman.report causes an error. It doesn’t matter whether I use a pre-configurated notify service or the overwrite feature. However, the messages are sent.

Watchman version 0.6.3
HA version 2024.8.1 Supervised

Examples:

```
action: watchman.report
data:
  create_file: false
  send_notification: true

service: watchman.report
data:
  create_file: false
  send_notification: true
  service: notify.gmail
```

Logs:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.watchman
Quelle: custom_components/watchman/__init__.py:425
Integration: Watchman (Dokumentation, Probleme)
Erstmals aufgetreten: 11:30:05 (12 Vorkommnisse)
Zuletzt protokolliert: 12:05:11

Unable to call service notify.persistent_notification due to an error.
Unable to call service notify.gmail due to an error.
```
