### ISSUE TITLE
Can't send Telegram report

### ISSUE THREAD

**Issue by sermayoral** [dummylabs/thewatchman#15]
After executing the following service:

```
service: watchman.report
data:
  send_notification: true
  data:
    parse_mode: html
```

The report file is generated, but the telegram notification doesn't work:

```
Logger: homeassistant.components.telegram_bot
Source: components/telegram_bot/__init__.py:587
Integration: Telegram bot (documentation, issues)
First occurred: 10:26:02 (1 occurrences)
Last logged: 10:26:02

Error sending message: Can't parse entities: can't find end of the entity starting at byte offset 283. Args: (10464662, '-== Reporte Watchman ==- \n\n-== Congratulations, all 53 services from your config are available!\n\n-== Missing 3 entity(ies) from 258 found in your config:\ndevice_tracker.nmap_joaquina [missing] in: automations.yaml:58\ndevice_tracker.nmap_pedro [missing] in: automations.yaml:59\nbinary_sensor.lluvia [missing] in: automations.yaml:998,1006,1043\n\n\n-== Report created on 23 Feb 2022 10:26:02\n-== Parsed 180 files in 1.86s., ignored 25 files \n-== Generated in: 0.00s. Validated in: 0.01s.'), kwargs: {'parse_mode': 'Markdown', 'disable_web_page_preview': None, 'disable_notification': False, 'reply_to_message_id': None, 'reply_markup': None, 'timeout': None}
```

**Comment by dummylabs** [comment]
Hey @sermayoral, both service and data should be defined in service call to override UI settings.  You can see from the trace log that telegram bot tries to use `parse_mode:markdown` instead of HTML.
Try to run the report like this:
```
service: watchman.report
data:
  send_notification: true
  service: telegram_bot.send_message
  data:
    parse_mode: html
```

Explanation: `data` is only makes sense for watchman when `service` parameter is set in the report call, otherwise `data` is ignored and watchman uses service settings from UI or yaml. It was done intentionally so that users do not mix `service` name from from UI and `data` from service call. 

This still sounds confusing, I know. Probably I'll add an additional warning/error message when `data` is used without `service`.

**Comment by dummylabs** [comment]
Another idea how to fix this confusion in future is to move `data` under the `service` parameter (breaking change):

```
service: watchman.report
data:
  send_notification: true
  service:
    name: telegram_bot.create_message
    data:
      parse_mode: html
```

This will make report call with notification service parameter slightly more complicated, but more clear, IMO:
```
service: watchman.report
data:
  send_notification: true
  service:
    name: telegram_bot.create_message
```

instead of

```
service: watchman.report
data:
  send_notification: true
  service: telegram_bot.create_message
```

**Comment by sermayoral** [comment]
Thanks @dummylabs. It has sense.

But, so, the problem is firstly i tried this: 

![image](https://user-images.githubusercontent.com/30116095/155308333-4175e85e-8f91-474a-b5ea-31b06dd01afb.png)

And the following service call:

```
service: watchman.report
data:
  send_notification: true
```

But it seems that it doesn't like the attribute 'parse_mode' defined in the UI:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:141
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:07:24 (2 occurrences)
Last logged: 12:09:03

[547839464736] Error handling message: extra keys not allowed @ data['parse_mode']. Got None
```

**Comment by sermayoral** [comment]
I have also tried this, as you mentioned:

```
service: watchman.report
data:
  send_notification: true
  service: notify.telegram_sergio
  data:
    parse_mode: html
```

With same result:

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:1375
First occurred: 12:15:54 (1 occurrences)
Last logged: 12:15:54

websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['parse_mode']
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:141
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:15:54 (1 occurrences)
Last logged: 12:15:54

[547839464736] Error handling message: extra keys not allowed @ data['parse_mode']. Got None
```
