### ISSUE TITLE
 Unable to write report: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by PacmanForever** [dummylabs/thewatchman#168]
Hi,

the last version (v0.6.5 2024-11-25) show the title error when executes the below code:

```
action: watchman.report
data:
  parse_config: true
  action: persistent_notification.create
  data:
    title: Watchman Report
  chunk_size: 3500
  create_file: true
```

HASSIOS 2024.11.3
