### ISSUE TITLE
variablename.split is missing

### ISSUE THREAD

**Issue by scottgrobinson** [dummylabs/thewatchman#30]
The report is telling me zone.split is a missing entity when, it's not an entity. Only the 1st zone.split is throwing the error, the other is fine.

```
action:
  - variables:
      zone: "{{ trigger.zone.attributes.friendly_name }}"
  - service: notify.alexa_media
    data:
      target:
        - group.all_alexa
      message: >
        {{ 'XXX is approaching home - ' + zone.split('Km Radius')[0].split('Home')[1] + 'k' }}
      data:
        type: tts
        method: all
  - service: notify.XXX
    data:
      message: >
        {{ 'XXX is approaching ' + zone.split('Km Radius')[0] + 'Km'}}
```
