### ISSUE TITLE
Detect scenes created as part of a script/automation

### ISSUE THREAD

**Issue by dannytsang** [dummylabs/thewatchman#34]
I'm not sure if this is possible. I would like watchman to have an option or be able to detect scenes created in a script or automation and not flag those scene as missing.

My example is it creates a new scene `service: scene.create ` based on the current entity states in the `snapshot_entities` parameter.

I have added the scene entity to the ignore list which also works.

My full script:
```
lounge_flash_lounge_lights_green:
    alias: "Lounge: Flash Lounge Lights Green"
    sequence:
      - service: scene.create
        data:
          scene_id: current_lounge_lights
          snapshot_entities:
            - light.lounge_left_lamp
            - light.lounge_right_lamp
      - service: scene.turn_on
        target:
          entity_id: scene.lounge_lights_green
        data:
          transition: 0
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500
      - service: scene.turn_on
        target:
          entity_id: scene.current_lounge_lights
    mode: single
    icon: mdi:lamp
```

Watchman report extract:
```
+--------------------------------+---------+--------------------------------+
| Entity ID                      | State   | Location                                                     |
+--------------------------------+---------+--------------------------------+
| scene.current_lounge_lights    | missing | scripts.yaml:217
```
