### ISSUE TITLE
It seems like unavailable covers are not being detected, e.g. cover.living_room_blinds

### ISSUE THREAD

**Issue by ndbroadbent** [dummylabs/thewatchman#64]
I have an automation that contains:

```
      - service: cover.close_cover
        data: {}
        target:
          entity_id: cover.living_room_blinds
```

Something went wrong with my blinds, and they are all unavailable now, but not showing up in the watchman report. Would it be possible to check for `cover.*`? Thanks!
