### ISSUE TITLE
Entities in templates not picked-up

### ISSUE THREAD

**Issue by andriej** [dummylabs/thewatchman#73]
Watchman seems to not pick-up entities that are used in templates/automations like:
```
states.sensor.entity_id.state
```
Maybe regex with states.* could help.

Anyway, thanks for awesome integration!

**Comment by dummylabs** [comment]
Hey @andriej, Watchman 0.6 should capture entities referenced by states.*, it was fixed in #32. Could you please add more details: 
- the fragment of the yaml with entity reference
- whether a real entity is present in the report as missing or a missing entity is not reported
Thanks!

**Comment by andriej** [comment]
I did a lot of fixing since that time and may not have the code anymore, but some more examples:

1. watchman reports 'camera.split' missing:
```
  - variables:
      file: /media/snapshots/{{ now().strftime('%Y_%m') }}/{{ camera.split('.')[1]
        }}_{{ now().strftime('%d_%H%M%S') }}.jpg
  - service: camera.snapshot
    data:
      entity_id: camera.{{ camera.split('.')[1] }}
      filename: '{{ file }}'
```

2. same for esphome:
```
| switch.is_on                   | missing | esphome/domofon.yaml:73,100                                  |
| switch.template                | missing | esphome/domofon.yaml:127,131                                 |
```
example of line:
```
    on_press:
      then:
        if:
          condition:
            switch.is_on: auto_open
          then:
            - delay: 1s
            - switch.turn_on: unlock
```
also other custom components are picked up:
```
| camera.generic_stream          | missing | custom_components/webrtc/services.yaml:20,66                 |
| media_player.mibox4            | missing | custom_components/webrtc/services.yaml:51                    |
| camera.living_room_camera      | missing | custom_components/yi_hack/services.yaml:9,47,71              |
```

maybe it's worth adding 'ignore' on esphome and custom_components or just leave it like that :-) 
I wanted to have clean report tho so make sure no mistakes are here after those few years with HA.

I do not have the faulty code anymore, but will try to reproduce when have some more time
