### ISSUE TITLE
missing_entities exceed maximum size of 16384 bytes

### ISSUE THREAD

**Issue by pickonedev** [dummylabs/thewatchman#87]
Hi!

Anyone knows about this problem? I get more than 1500 warnings per day in the log, about this... Any solution?

`State attributes for sensor.watchman_missing_entities exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored`

**Comment by swa72** [comment]
Yep, same here. Latest version 2023.4.1

**Comment by otiswrx** [comment]
I am also seeing this frequently in my logs. Will try the exclude option and see if that clears the warning.

**Comment by pickonedev** [comment]
`  exclude:
    entity_globs:
      - sensor.watchman*`
indeed solve the problem, like alex said.

**Comment by thargy** [comment]
Alternatively, less drastic is:
```yaml
# Don't include watchman results in recorder as they're too big!
recorder:
  exclude:
    entities:
      - sensor.watchman_missing_entities
      - sensor.watchman_missing_services
```

Which leaves `sensor.watchman_last_updated` in the recorder, which is potentially helpful and does not grow out of control.
