### ISSUE TITLE
Feature Request alexa.yaml include_entities and entity_config

### ISSUE THREAD

**Issue by TBobsin** [dummylabs/thewatchman#88]
Hello 
If you have many devices, the optional part below entity_config: is quickly forgotten or overlooked. 
Therefore, it would be good if the missing optional entry is displayed. 

Example:
```
alexa:
smart_home:
include_entities:
  - light.tv_lamp
  - light.floor_lamp
  - switch.smartplug

entity_config:
  light.tv_lamp:
   name: "tv_lamp
   display_categories: LIGHT
   description: "Lamp next to the TV

   switch.smartplug:
     name: "My Smartplug"
     display_categories: LIGHT
```

Here the light.floor_lamp is missing under entity_config: - that should definitely be displayed in Watchman.

The entity_config: only makes sense if the other attributes are set. Therefore, please also check whether they are present. 
The display_categories: is probably SMARTPLUG instead of LIGHT 
The description is missing for the smartplug. 

Homeassistant also does not check whether the include_entities: exist in HA. For example, I had accidentally written "TV lamps" (more number), so Alexa has not recognized the lamp. 

Thanks for the good work
