### ISSUE TITLE
Ignore entities followed by a Jinja concatenation operator

### ISSUE THREAD

**Issue by dummylabs** [dummylabs/thewatchman#89]
Quoted entity names followed by either '+' or '~' operator most probably are only a part of real entity name and should not be added to the report as missing. Example: `'sensor.weather_' ~ location`

**Comment by tinuva** [comment]
+1 

I get a similar error on the following piece of automation code. `timer.morning_ [missing] morning_routine.yaml`
```yaml
    action:
      - service: light.turn_on
        data_template:
          entity_id: "{{ trigger.event.data.entity_id|replace('timer.morning_', 'light.') }}"
          brightness_pct: 100
```
